### ISSUE TITLE
I have tried tinify, but found 'module' object has no attribute 'from_file' 

### ISSUE THREAD

**Issue by njafei** [tinify/tinify-python#1]
tinify is installed

$ pip show tinify
Name: tinify
Version: 1.1.0
Location: /Library/Python/2.6/site-packages
Requires: requests

but when i use it by:
source = tinify.from_file("test.png")
only found that :'module' object has no attribute 'from_file' 

did i do something wrong?

**Comment by middagj** [comment]
Hi,
It seems that our module singleton isn't used. I assume you do a `import tinify` before you use it. Could you try to use `from tinify import tinify`. Which version of Python are you at?

**Comment by dotneB** [comment]
Sorry to revive this old thread, but I had the exact same issue. It turn out it was my fault, I had named my own test script tinify.py that was causing python to search for from_file in my own script.

**Comment by jippeholwerda** [comment]
@dotneB Thanks for sharing. @njafei Does this resolve your issue?
