### ISSUE TITLE
Tinify "fit" example from API reference doesn't work

### ISSUE THREAD

**Issue by SIRHAMY** [tinify/tinify-python#10]
I created a test program on my machine to verify behavior but it doesn't seem to work. It does seem to be going to the API and getting compressed, but the original dimensions seem to be preserved, meaning "fit" isn't being respected.

Test program:
```
import tinify

tinify.key = "SECRETKEY"
source = tinify.from_file("./resources/images/blah.jpg")
source.resize(
    method="scale",
    width=150
)
source.to_file("./output/output.jpg")
```

I then tested with "scale" and "cover" and both of those have the same behavior - compresssing but not actually mutating the image, making me think that the action word just isn't being passed down.

**Comment by emielvanlankveld** [comment]
Hi! Thank you for reaching out. Specifying only a width or a height (but not both) is only supported with the `scale` method. For the `fit`, `cover` and `thumb` methods you'll need to provide both a target width and height. You can find more detailed documentation here:

https://tinypng.com/developers/reference/python#resizing-images

Good luck!
