### ISSUE TITLE
Image grows in size after compressing

### ISSUE THREAD

**Issue by eshaben** [tinify/tinify-python#14]
After calling `tinify.from_file(image)` on a few different images the image actually gets larger.

Here is one of the images that grew in size: https://docs.moonbeam.network/images/tokens/connect/mathwallet/mathwallet-5.png

The original file size is: 1050.744140625KB and after the compression the size grows to: 1059.2841796875KB

Is there a reason why the image size increased? I think at the very least, if the image grows in size after compressing, the original image should be returned instead.

**Comment by stdagkalakis** [comment]
Good morning,

The developer API will not return an optimized image if it is larger than the original.

We run your example image both by downloading and using the from_URL function and we can't reproduce your issue.

If you are still experiencing the issue please kindly reach out to our support at support@tinify.com with more details
and a screenshot of your code.

Thanks!
