### ISSUE TITLE
webp does not  support,  any solution? thx

### ISSUE THREAD

**Issue by tomnkey** [tinify/tinify-python#22]
![image](https://github.com/tinify/tinify-python/assets/3223174/a086284f-719d-454e-889c-65474fb22549)

**Comment by StevenVanBlijderveen** [comment]
Hi tomnkey,

As your image title suggests you are uploading an animated WebP. Tinify does not support these images for now, only static WebP's. We are looking to add this feature to our products, but have no estimated time on when this will happen yet.

Sorry I couldn't be of any further help!
