### ISSUE TITLE
python 2.6 support?

### ISSUE THREAD

**Issue by lbillingham** [tinify/tinify-python#5]
Hello, 

The tinify page on [PyPi](https://pypi.python.org/pypi/tinify) suggests that python 2.6 is still supported.

However, I'm getting

```shell
  File "./tinify-test.py", line 28, in <module>
    source = tinify.from_file(uncompressed_path)
  File "/home/.../tinify_venv/lib/python2.6/site-packages/tinify/__init__.py", line 79, in from_file
    return Source.from_file(path)
  File "/home/.../tinify_venv/lib/python2.6/site-packages/tinify/source.py", line 14, in from_file
    return cls._shrink(f.read())
  File "/home/.../tinify_venv/lib/python2.6/site-packages/tinify/source.py", line 26, in _shrink
    response = tinify.get_client().request('POST', '/shrink', obj)
  File "/home/.../tinify_venv/lib/python2.6/site-packages/tinify/client.py", line 64, in request
    raise ConnectionError('Error while connecting: {0}'.format(err), cause=err)
tinify.errors.ConnectionError: Error while connecting: request() keywords must be strings
```
with 
```shell
$ python --version
Python 2.6.4
```
and 

```shell
$ pip freeze
requests==2.14.2
tinify==1.5.0
wsgiref==0.1.2
```
looks like it might be similar to closed issue #2 

I don't get the error in a python 2.7 virtualenvironment

**Comment by warflower** [comment]
Hi Laurence,

I was only able to install Python 2.6.6 using pyenv, but for me it is working fine using that version.

As you can see on https://travis-ci.org/tinify/tinify-python, our plugin is automatically tested with Python 2.6 as well, and the tests are succeeding without any problems. Other than your report, we therefore have no indications that the library shouldn't be working fine with Python 2.6.
Either something drastically changed between versions 2.6.4 and 2.6.6, or something else is different in your Python 2.6.4 environment that is causing this error.

Looking at your trace it looks like Python is complaining about the types of the variables used when attempting to compress a local file. If you have some programming knowledge, you could try to debug to see what kind of datatypes are used for the arguments in the `self.session.request(method, url, **params)`
call in `client.py`.

On another note, I would suggest you to upgrade Python, as you're using a very old version of Python that has been receiving security updates for more than 3 years now.

**Comment by lbillingham** [comment]
after a bit of digging it to do with `str` vs `bytes` in the keys of the `request` `params`.

as a workaround we can do a 

```python
params = dict((str(k), v) for k,v in params.iteritems())
```
before sending the request in the line 56 of `client.py`

RE: using a version of python with post-2008 bugfixes/features.... yes that would be _much_ _much_ better but unfortunately not always possible
