### ISSUE TITLE
Service is adding invalid Expires header

### ISSUE THREAD

**Issue by mc962** [tinify/tinify-python#8]
I am using the Tinify python package to compress images, after which it uploads them to our S3 bucket. The `store` method is used.

I am finding the Tinify is adding an `Expires` header with a value string of `Invalid Date` to the metadata for the S3 object. This breaks some downstream services that parse headers on the object, as they do not expect this bad value. I think this started to be noticed towards the beginning of November 2018.

I was able to bypass it in the ruby version of the package by manually specifying the header value in the `store` method, which sets a proper value. However, this shouldn't be required...and from what I can tell it wasn't even a present header on uploaded objects in the past before this error started happening.

**Comment by rolftimmermans** [comment]
Hey, thanks for reporting this! Based on your feedback we have fixed the issue in the API. The `Expires` header should no longer be set on objects unless it is explicitly included inside the `headers` key within the `store` action.

Please let us know if this resolves your issue and if you have any other questions!

**Comment by mc962** [comment]
Thanks a lot for the quick response. 

That fix seems to be working, I'm not seeing any more rogue Expires headers on new S3 objects.

**Comment by rolftimmermans** [comment]
Great, thanks for your feedback!
